default: &default
  clients:
    default:
      database: example_default
      hosts:
        - localhost:27017
      options:
  options:

development:
  clients:
    default:
      database: example_dev
      hosts:
        - localhost:27017
      options:
  options:

test:
  clients:
    default:
      database: example_test
      hosts:
        - localhost:27017
      options:
  options:

production:
  clients:
    default:
      database: example_production
      hosts:
        - localhost:27017
      options:
  options:
